image: "golang:1.14.2"

stages:
  - test
  - build

before_script:
  - mkdir -p /go/src/github.com/bluearchive /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/github.com/bluarchive/ci-cd-test
  - ln -s /go/src/github.com/bluearchive /go/src/_/builds/ci-cd-test
  - make dep

unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race

code_coverage:
  stage: test
  script:
    - make coverage

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
    - master

lint_code:
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - make